SELECT 
COLUMN_NAME, 
DATA_TYPE AS TYPE, 
	CASE WHEN IS_NULLABLE = 'YES' THEN 'Y' 
	ELSE 'N' END NULL_YN,  
CHARACTER_MAXIMUM_LENGTH AS DATA_LENGTH,  
	CASE WHEN COLUMN_KEY = 'PRI' THEN 'Y' 
	END PK,  
COLUMN_COMMENT AS COMMENTS 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE 1=1 
AND TABLE_SCHEMA = DATABASE() 
AND TABLE_NAME = ':tableName' 
ORDER BY ORDINAL_POSITION