/**
 * 
 */
package com.kyj.fx.voeditor.visual.component.text;

import java.io.File;

import com.google.common.io.Files;

/**
 * 
 * xlst convert program.
 * 
 * @author KYJ
 */

public class XsltTransformCompositeSamples {
	static String xmlDataSample() {
		StringBuffer sb = new StringBuffer();
		sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
		sb.append("<catalog>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Empire Burlesque</title>\n");
		sb.append("    <artist>Bob Dylan</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <company>Columbia</company>\n");
		sb.append("    <price>10.90</price>\n");
		sb.append("    <year>1985</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Hide your heart</title>\n");
		sb.append("    <artist>Bonnie Tyler</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>CBS Records</company>\n");
		sb.append("    <price>9.90</price>\n");
		sb.append("    <year>1988</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Greatest Hits</title>\n");
		sb.append("    <artist>Dolly Parton</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <company>RCA</company>\n");
		sb.append("    <price>9.90</price>\n");
		sb.append("    <year>1982</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Still got the blues</title>\n");
		sb.append("    <artist>Gary Moore</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Virgin records</company>\n");
		sb.append("    <price>10.20</price>\n");
		sb.append("    <year>1990</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Eros</title>\n");
		sb.append("    <artist>Eros Ramazzotti</artist>\n");
		sb.append("    <country>EU</country>\n");
		sb.append("    <company>BMG</company>\n");
		sb.append("    <price>9.90</price>\n");
		sb.append("    <year>1997</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>One night only</title>\n");
		sb.append("    <artist>Bee Gees</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Polydor</company>\n");
		sb.append("    <price>10.90</price>\n");
		sb.append("    <year>1998</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Sylvias Mother</title>\n");
		sb.append("    <artist>Dr.Hook</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>CBS</company>\n");
		sb.append("    <price>8.10</price>\n");
		sb.append("    <year>1973</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Maggie May</title>\n");
		sb.append("    <artist>Rod Stewart</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Pickwick</company>\n");
		sb.append("    <price>8.50</price>\n");
		sb.append("    <year>1990</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Romanza</title>\n");
		sb.append("    <artist>Andrea Bocelli</artist>\n");
		sb.append("    <country>EU</country>\n");
		sb.append("    <company>Polydor</company>\n");
		sb.append("    <price>10.80</price>\n");
		sb.append("    <year>1996</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>When a man loves a woman</title>\n");
		sb.append("    <artist>Percy Sledge</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <company>Atlantic</company>\n");
		sb.append("    <price>8.70</price>\n");
		sb.append("    <year>1987</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Black angel</title>\n");
		sb.append("    <artist>Savage Rose</artist>\n");
		sb.append("    <country>EU</country>\n");
		sb.append("    <company>Mega</company>\n");
		sb.append("    <price>10.90</price>\n");
		sb.append("    <year>1995</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>1999 Grammy Nominees</title>\n");
		sb.append("    <artist>Many</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <company>Grammy</company>\n");
		sb.append("    <price>10.20</price>\n");
		sb.append("    <year>1999</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>For the good times</title>\n");
		sb.append("    <artist>Kenny Rogers</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Mucik Master</company>\n");
		sb.append("    <price>8.70</price>\n");
		sb.append("    <year>1995</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Big Willie style</title>\n");
		sb.append("    <artist>Will Smith</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <company>Columbia</company>\n");
		sb.append("    <price>9.90</price>\n");
		sb.append("    <year>1997</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Tupelo Honey</title>\n");
		sb.append("    <artist>Van Morrison</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Polydor</company>\n");
		sb.append("    <price>8.20</price>\n");
		sb.append("    <year>1971</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Soulsville</title>\n");
		sb.append("    <artist>Jorn Hoel</artist>\n");
		sb.append("    <country>Norway</country>\n");
		sb.append("    <company>WEA</company>\n");
		sb.append("    <price>7.90</price>\n");
		sb.append("    <year>1996</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>The very best of</title>\n");
		sb.append("    <artist>Cat Stevens</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Island</company>\n");
		sb.append("    <price>8.90</price>\n");
		sb.append("    <year>1990</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Stop</title>\n");
		sb.append("    <artist>Sam Brown</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>A and M</company>\n");
		sb.append("    <price>8.90</price>\n");
		sb.append("    <year>1988</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Bridge of Spies</title>\n");
		sb.append("    <artist>T`Pau</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Siren</company>\n");
		sb.append("    <price>7.90</price>\n");
		sb.append("    <year>1987</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Private Dancer</title>\n");
		sb.append("    <artist>Tina Turner</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>Capitol</company>\n");
		sb.append("    <price>8.90</price>\n");
		sb.append("    <year>1983</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Midt om natten</title>\n");
		sb.append("    <artist>Kim Larsen</artist>\n");
		sb.append("    <country>EU</country>\n");
		sb.append("    <company>Medley</company>\n");
		sb.append("    <price>7.80</price>\n");
		sb.append("    <year>1983</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Pavarotti Gala Concert</title>\n");
		sb.append("    <artist>Luciano Pavarotti</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>DECCA</company>\n");
		sb.append("    <price>9.90</price>\n");
		sb.append("    <year>1991</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>The dock of the bay</title>\n");
		sb.append("    <artist>Otis Redding</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <COMPANY>Stax Records</COMPANY>\n");
		sb.append("    <PRICE>7.90</PRICE>\n");
		sb.append("    <YEAR>1968</YEAR>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Picture book</title>\n");
		sb.append("    <artist>Simply Red</artist>\n");
		sb.append("    <country>EU</country>\n");
		sb.append("    <company>Elektra</company>\n");
		sb.append("    <price>7.20</price>\n");
		sb.append("    <year>1985</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Red</title>\n");
		sb.append("    <artist>The Communards</artist>\n");
		sb.append("    <country>UK</country>\n");
		sb.append("    <company>London</company>\n");
		sb.append("    <price>7.80</price>\n");
		sb.append("    <year>1987</year>\n");
		sb.append("  </cd>\n");
		sb.append("  <cd>\n");
		sb.append("    <title>Unchain my heart</title>\n");
		sb.append("    <artist>Joe Cocker</artist>\n");
		sb.append("    <country>USA</country>\n");
		sb.append("    <company>EMI</company>\n");
		sb.append("    <price>8.20</price>\n");
		sb.append("    <year>1987</year>\n");
		sb.append("  </cd>\n");
		sb.append("</catalog>\n");
		return sb.toString();
	}

	static String xsltSample() {
		
		String baseLocation = System.getProperty("user.dir");
		baseLocation = baseLocation.replaceAll("\\\\", "/");
		
		StringBuffer sb = new StringBuffer();
		sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
		sb.append("<xsl:stylesheet version=\"1.0\"\n");
		sb.append("xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">\n");
		sb.append("<xsl:template match=\"/\">\n");
		sb.append("  <html>\n");
		sb.append("<header>\n");
		sb.append("<script type=\"text/javascript\" src=\"file:///"+baseLocation+"/javascript/jqplot/jquery.min.js\"></script>\n");
		sb.append("<script type=\"text/javascript\" src=\"file:///"+baseLocation+"/javascript/jqplot/jquery.jqplot.js\"></script>\n");
		sb.append("<script type=\"text/javascript\" src=\"file:///"+baseLocation+"/javascript/jqplot/plugins/jqplot.barRenderer.js\"></script>\n");
		sb.append("<script type=\"text/javascript\" src=\"file:///"+baseLocation+"/javascript/jqplot/plugins/jqplot.pieRenderer.js\"></script>\n");
		sb.append("<script type=\"text/javascript\" src=\"file:///"+baseLocation+"/javascript/jqplot/plugins/jqplot.categoryAxisRenderer.js\"></script>\n");
		sb.append("<script class=\"include\" type=\"text/javascript\" src=\"file:///"+baseLocation+"/javascript/jqplot/plugins/jqplot.pointLabels.js\"></script>\n");
		sb.append("<link  rel=\"stylesheet\" type=\"text/css\" href=\"file:///"+baseLocation+"/javascript/jqplot/jquery.jqplot.min.css\" />\n");
		sb.append("<script type=\"text/javascript\">\n");
		sb.append("\n");
		sb.append("\n");
		sb.append("$(document).ready(function(){\n");
		sb.append("        var s1 = [<xsl:for-each select=\"catalog/cd\"><xsl:if test=\"position()&lt;=4\"><xsl:text>'</xsl:text><xsl:value-of select=\"year\"/><xsl:text>',</xsl:text></xsl:if></xsl:for-each>];\n");
		sb.append("        var ticks = [ <xsl:for-each select=\"catalog/cd\"><xsl:if test=\"position()&lt;=4\"><xsl:text>'</xsl:text><xsl:value-of select=\"title\"/><xsl:text>',</xsl:text></xsl:if></xsl:for-each>];\n");
		sb.append("\n");
		sb.append("        plot7 = $.jqplot('chart3', [s1], {\n");
		sb.append("            seriesDefaults:{\n");
		sb.append("                renderer:$.jqplot.BarRenderer,\n");
		sb.append("                rendererOptions: { fillToZero: true },\n");
		sb.append("                    pointLabels: { show: true }\n");
		sb.append("            },\n");
		sb.append("            axes: {\n");
		sb.append("                yaxis: { autoscale: true },\n");
		sb.append("                xaxis: {\n");
		sb.append("                    renderer: $.jqplot.CategoryAxisRenderer,\n");
		sb.append("                    ticks: ticks\n");
		sb.append("                }\n");
		sb.append("            }\n");
		sb.append("        });\n");
		sb.append("    });\n");
		sb.append("</script>\n");
		sb.append("</header>\n");
		sb.append("\n");
		sb.append("  <body>\n");
		sb.append("\n");
		sb.append("\n");
		sb.append("\n");
		sb.append("<div id=\"chart3\">  </div>\n");
		sb.append("<text>this is text field</text>\n");
		sb.append("    <table border=\"1\">\n");
		sb.append("      <tr bgcolor=\"#9acd32\">\n");
		sb.append("        <th>Title</th>\n");
		sb.append("        <th>Artist</th>\n");
		sb.append("      </tr>\n");
		sb.append("      <xsl:for-each select=\"catalog/cd\">\n");
		sb.append("\n");
		sb.append("<xsl:if test=\"position()&lt;=4\">\n");
		sb.append("      <tr>\n");
		sb.append("        <td><xsl:value-of select=\"title\"/></td>\n");
		sb.append("        <td><xsl:value-of select=\"artist\"/></td>\n");
		sb.append("      </tr>\n");
		sb.append("</xsl:if>\n");
		sb.append("\n");
		sb.append("      </xsl:for-each>\n");
		sb.append("    </table>\n");
		sb.append("  </body>\n");
		sb.append("  </html>\n");
		sb.append("</xsl:template>\n");
		sb.append("</xsl:stylesheet>\n");

		
		return sb.toString();
	}
}
