
CREATE TABLE  IF NOT EXISTS `tbp_sys_dao_methods_h` (
	`HIST_TSP`	TEXT NOT NULL,
	`PACKAGE_NAME`	TEXT NOT NULL,
	`CLASS_NAME`	TEXT NOT NULL,
	`METHOD_NAME`	TEXT NOT NULL,
	`RESULT_VO_CLASS`	TEXT DEFAULT NULL,
	`SQL_BODY`	TEXT,
	`METHOD_DESC`	TEXT,
	`DML_TYPE`	TEXT,
	`FST_REG_DT`	INTEGER DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(HIST_TSP,PACKAGE_NAME,CLASS_NAME,METHOD_NAME)
);

CREATE TABLE IF NOT EXISTS `tbp_sys_dao_methods` (
	`PACKAGE_NAME`	TEXT NOT NULL,
	`CLASS_NAME`	TEXT NOT NULL,
	`METHOD_NAME`	TEXT NOT NULL,
	`RESULT_VO_CLASS`	TEXT NOT NULL,
	`SQL_BODY`	TEXT,
	`METHOD_DESC`	TEXT,
	PRIMARY KEY(PACKAGE_NAME,CLASS_NAME,METHOD_NAME)
);
CREATE TABLE IF NOT EXISTS "tbp_sys_dao_fields" (
	`PACKAGE_NAME`	TEXT NOT NULL,
	`CLASS_NAME`	TEXT NOT NULL,
	`METHOD_NAME`	TEXT NOT NULL,
	`FIELD_NAME`	TEXT NOT NULL,
	`TEST_VALUE`	TEXT DEFAULT NULL,
	PRIMARY KEY(PACKAGE_NAME,CLASS_NAME,METHOD_NAME,FIELD_NAME)
);
CREATE TABLE IF NOT EXISTS `tbp_sys_dao_columns` (
	`PACKAGE_NAME`	TEXT,
	`CLASS_NAME`	TEXT,
	`METHOD_NAME`	TEXT,
	`COLUMN_NAME`	TEXT,
	`COLUMN_TYPE`	TEXT,
	PRIMARY KEY(PACKAGE_NAME,CLASS_NAME,METHOD_NAME,COLUMN_NAME)
);
CREATE TABLE IF NOT EXISTS "tbm_sys_dao" (
	`PACKAGE_NAME`	TEXT NOT NULL,
	`CLASS_NAME`	TEXT NOT NULL,
	`LOCATION`	TEXT DEFAULT NULL,
	`CLASS_DESC`	TEXT,
	`TABLE_NAME`	TEXT DEFAULT NULL,
	PRIMARY KEY(PACKAGE_NAME,CLASS_NAME)
);


