CREATE TABLE `tbp_sys_dao_columns` (
	`PACKAGE_NAME` VARCHAR(200) NOT NULL,
	`CLASS_NAME` VARCHAR(50) NOT NULL,
	`METHOD_NAME` VARCHAR(50) NOT NULL,
	`COLUMN_NAME` VARCHAR(50) NOT NULL,
	`COLUMN_TYPE` VARCHAR(50) NULL DEFAULT NULL,
	`PROGRAM_TYPE` VARCHAR(30) NULL DEFAULT NULL,
	`LOCK_YN` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`PACKAGE_NAME`, `CLASS_NAME`, `METHOD_NAME`, `COLUMN_NAME`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
